### PR TITLE
See https://www.jfrog.com/jira/browse/RTFACT-6025

### PR DESCRIPTION
**Pull request by charlesk40**

### CODE REVIEW

**Comment by eyalbe4** [comment]
@charlesk40, thank you for this pull request.
Can you please sign JFrog's CLA so that we can merge the code?
You can do it through [this link](http://www.jfrog.com/confluence/display/OSS/How+to+Contribute).

**Comment by charlesk40** [comment]
@eyalbe4   I did sign the CLA a long ago.  I have the copy of it.  Do you need me to sign it again? Thanks.

**Comment by eyalbe4** [comment]
@charlesk40,
We apologize for not being able to find your signed CLA. Could you please sign it again?
Thanks!

**Comment by charlesk40** [comment]
@eyalbe4   I just signed it again.  Thanks

**Comment by charlesk40** [comment]
@eyalbe4 Thanks so much for merging.  How long does it take for it to show up in bintray?

**Comment by eyalbe4** [comment]
@charlesk40, we will create a new release of the client and have it published to Bintray in a few hours. We'll notify you when it is there.

**Comment by eyalbe4** [comment]
@charlesk40, version 1.1.0 of the client is now [available on Bintray](https://bintray.com/jfrog/artifactory-tools/artifactory-client-java). Thanks again for the contribution.

**Pull request merged**
