### PR TITLE
Fixed usability of Replications

### PR DESCRIPTION
**Pull request by zonArt**
- Made the constructors public
- Updated the documentation to reflect usage

### CODE REVIEW

**Comment by zonArt** [comment]
@eyalbe4, may I kindly ask you to check/merge this PR ? Is it something I can do/change to have it merged ? I'm conscious that it may lack some tests and/or the global philosophy of the library is not fully respected but it would really help if I can get this modification in the next release.
Thank you in advance for your support

**Comment by eyalbe4** [comment]
@zonArt,
Thanks for submitting this. We'll look into your pull request soon.

**Comment by eyalbe4** [comment]
Thanks for this pull request @zonArt.
What is the reason for your suggested changed in the usage examples in the README?
Your change replaces the "builder" approach with a constructor that receives all of the instance arguments.
Isn't using a builder instance more convenient? (especially when the entity can receive a lot of arguments).

**Comment by zonArt** [comment]
Yes of course I would prefer a builder, however it is not existing (or I missed it) in  @fritaly 's proposal and I wasn't feeling writing it myself and I proposed this PR in order to make it usable without writing a builder.

**Comment by zonArt** [comment]
@fritaly Can I ask you how am I supposed to use these `(Remote|Local)ReplicationImpl` as following your documentation doesn't work ? I guess that as you proposed that, you tested it successfully so you know how it should be used. I'm sorry, as you can notice I'm not skilled enough to get it straight from the code (although it's probably obvious or something is really missing).

**Comment by fritaly** [comment]
Hi @zonArt, I just realized that the API is not complete hence your issues.

I hadn't noticed this myself because the tests I implemented (in Groovy) can access the private fields. 

The fact that the API is implemented in Java and the tests in Groovy hide this issue.

**Comment by fritaly** [comment]
@zonArt I pushed some commits on this [fork](https://github.com/fritaly/artifactory-client-java/tree/replication-builders) to create the missing builder classes.

Can you please test those changes prior I issue an official PR ?

**Comment by zonArt** [comment]
@fritaly Oh excellent I'll try this tomorrow thanks (not yet have watched the code though)

**Comment by zonArt** [comment]
@fritaly Looks excellent, thanks exactly what was missing, sorry for my proposal it was a quick and dirty hack. I now feel stupid not having been able to make it the right way myself. I didn't test to use the portion but I feel pretty confident, at least my ide wasn't complaining so it's a good first sign. Please post it "officially"

**Comment by fritaly** [comment]
Just created #157

**Pull request closed without merging**
