### PR TITLE
Use Artifactory API Key to login with artifactory.client (#102)

### PR DESCRIPTION
**Pull request by vincentfree**
Use Artifactory API Key to login. Linked issue #102

### CODE REVIEW

**Comment by vincentfree** [comment]
I was not able to use the included test, I also added my comments about this to #59.
I've added a testcase and also a TODO.
To really test this we have to hook onto the RESTClient to see if the header is set. We can assume that this does work but there is no other way to really test the functionality.

**Comment by eyalbe4** [comment]
Thanks for this pull request @vincentfree.
Artifactory allows authentication with API Key without the need of a username. Supplying the username works due to historical reasons, but there's probably no point in adding this API to the java-client. To authenticate with an API Key, all you need to do is to add a header named *X-JFrog-Art-Api* with the API Key as the value (which you already use). It might be better therefore to remove the "boolean apiKey" argument of the "create" method and add an additional signature of the method, so that one signature receives username and password and the other one receives an API Key.
We should also enable running the tests with an API Key instead of a user name and password. Currently, in the README.md we ask the users to set their credentials in these environment variables:
CLIENTTESTS_ARTIFACTORY_USERNAME and CLIENTTESTS_ARTIFACTORY_PASSWORD.
We should probably support an additional environment variable - CLIENTTESTS_ARTIFACTORY_API_KEY.

**Comment by eyalbe4** [comment]
Hi @vincentfree,
See my comments above.

**Comment by eyalbe4** [comment]
@vincentfree, I'm closing this pull request for now.

**Comment by vincentfree** [comment]
@eyalbe4 Sorry for not responding, that's ok when i come around to it i'll open a new pull request with the change you proposed.

**Comment by eyalbe4** [comment]
No worries @vincentfree. Thank you.

**Pull request closed without merging**
