### PR TITLE
Permission principals support

### LINKED ISSUE #54: There is no "principals" for the permission target builder
While i try to create new permission target i have no way to add user and group with permissions, cause it use the item permission and it's doesn't match the json file.
json file:
{
- "name": "populateCaches",
- "includesPattern": "**" (default),
- "excludesPattern": "" (default),
- "repositories": ["local-rep1", "local-rep2", "remote-rep1", "virtual-rep2"],
- "principals": {
      "users" : {
        "bob": ["r","w","m"],
        "alice" : ["d","w","n", "r"]
      },
      "groups" : {
        "dev-leads" : ["m","r","n"],
        "readers" : ["r"]
      }
  }
  }

what we get:
{
   "name": "test1",
   "includesPattern": "**" ,
   "excludesPattern": "" ,
   "repositories": ["new-local"],
   "itemPermissions": {
        "users" : {
          "test1": ["r","w","m"],
          "test2" : ["d","w","n", "r"],
          "test3" : ["r"]
        },
          "groups" : {
          "deployers" : ["m","r","n"],
          "users" : ["r"]
        }
    }
}

### PR DESCRIPTION
**Pull request by axel3rd**
Fix #54

Some API updates (name, content) for better understanding with UI screen => perhaps require a v2.2 upgrade.

**NB:** Updates done related to Artifactory v4.13 ; I didn't see any `ItemPermission` attributes in `api/security/permissions` API (by tests or [documentation](SecurityConfigurationJSON-application/vnd.org.jfrog.artifactory.security.PermissionTarget+json)) => deleted and replaced by `principals`

### CODE REVIEW

**Comment by axel3rd** [comment]
**NB:** Updates done related to Artifactory v4.13 ; I didn't see any `ItemPermission` attributes in `api/security/permissions` API (by tests or [documentation](SecurityConfigurationJSON-application/vnd.org.jfrog.artifactory.security.PermissionTarget+json)) => deleted and replaced by `principals`

**Comment by axel3rd** [comment]
Hi JFrog maintainers,

Is there a chance for an inclusion of this PR in a short term ?

Its availability in Jcenter could be very useful for using it in some Artifactory permissions management process.
(To be honest, I'm not fan to deploy some forked version of components in our repository ^^)

I'm available for any remarks, changes, ... 

Thanks in advance.
Best regards.

**Comment by eyalbe4** [comment]
Thanks for the pull request @axel3rd.
Question: What is the reason for renaming "PermissionTarget" to "Permission"? These API changes will force users user to modify the code, and I'm not sure this change is a must.

**Comment by axel3rd** [comment]
@eyalbe4 : The reason is to be more clear with the [REST API specification](https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-GetPermissionTargets), who is ``GET /api/security/permissions``, not ``GET /api/security/permissionsTarget``, and the UI labels.

As my understand (but perhaps this is a misunderstanding), the concept of *Target* is directly linked to the permissions associated to a resource/artifact => [ItemPermission](https://github.com/JFrogDev/artifactory-client-java/blob/master/api/src/main/java/org/jfrog/artifactory/client/model/ItemPermission.java) (*Effective Permissions* label in UI and client API)

But this is not linked to ``/api/security/permissions`` and not supported in [PermissionTarget](https://github.com/JFrogDev/artifactory-client-java/blob/master/services/src/main/java/org/jfrog/artifactory/client/model/impl/PermissionTargetImpl.java) (or perhaps in a old Artifactory version ...).

**Comment by axel3rd** [comment]
@eyalbe4 : Hi, I allow me a little *bump* :smile:. Is this PR receivable or I need to rework on it (see my previous comment) ? Thanks in advance.

**Comment by axel3rd** [comment]
I wish a gift like a merge of this PR for christmas :bowtie:.
But if some changes are required, I can do before end of year :innocent:.

**Comment by eyalbe4** [comment]
@axel3rd, we've just pushed a [commit](https://github.com/JFrogDev/artifactory-client-java/commit/c152a397bfb927c795aa5a8885a59038664e4f72) which is based on your pull request, with a few changes, The changes are mostly around different API names.
You've been waiting for a while for your code to be merged, so we wanted to make sure the code is merged quickly, and before christmas :)
Thanks again for your code contribution. We'd happy to accept more in the future!
We also want to send you a nice christmas present, so if you send me your mailing address, we'll send you a JFrog t-shirt :)

**Comment by axel3rd** [comment]
> You've been waiting for a while for your code to be merged, so we wanted to make sure the code is merged quickly, and before christmas :)

Youhou, so cool, I will try to test it ASAP (today/tomorrow) on my real use case.
If a SNAPSHOT exists in bintray, the link will help me (otherwise I need to reinstall some tools to build it).

> Thanks again for your code contribution. We'd happy to accept more in the future!

With pleasure.

> We also want to send you a nice christmas present, so if you send me your mailing address, we'll send you a JFrog t-shirt :)

Thanks ! How I can communicate it (private mail @ somebody?)

**Comment by eyalbe4** [comment]
@axel3rd,
You can download the latest snapshot from the *https://oss.jfrog.org/oss-snapshot-local* maven repository (you can also build the sources of course). 
You can send your mailing address to *eyalb@jfrog.com*. Thanks

**Comment by axel3rd** [comment]
Tested with ``2.3.x-SNAPSHOT``, it works like a charm (some logical trivial minor changes on ``Permission[Target]Builder``).

Many thanks for this // merge, I close this PR.

**Comment by axel3rd** [comment]
Fix #54 & #98

**Pull request closed without merging**
