### PR TITLE
#52 Adding GAVC and artifact version search.

### PR DESCRIPTION
**Pull request by ragesteel**

### CODE REVIEW

**Comment by eyalbe4** [comment]
Hi Igor,
Thanks a lot for your contribution!
We would like to merge your pull request, but please add the following so that we can do so:
1. Please add tests for the new search methods you added. Al of the existing search methods have tests, so please follow the existing examples to add your own.
2. Instead of initializing searchQuery map as an empty map in 2 of the new methods:
this.searchQuery = [:]
it might be better to do it once inside the search method, in case it is null.

In addition, please sign JFrog's CLA. You can do this through the following link:
http://www.jfrog.com/confluence/display/OSS/How+to+Contribute

**Comment by msteiger** [comment]
Any progress on this one? I think it would be great if it was part of the next official release.

**Comment by eyalbe4** [comment]
I agree. We're waiting for @ragesteel to add tests for the new API.

**Comment by padyx** [comment]
I just re-implemented GAVC search (similar to what @ragesteel did) and wanted to write those missing tests that this PR is missing.
But: How do we run it best? Because if I see this correctly, to run the tests, you need an Artifactory to run against? And the JFrog OSS version does not support hosting Docker images...
Is there a public test artifactory one can test against?

**Comment by eyalbe4** [comment]
Hi @padyx,
We've just modified the java-client tests so that they can be easily run agains a local Artifactory instance. We updated the README file with instructions for building and running the tests.
Since the java-client also includes support for pro-features, currently the tests can be run agains an Artifactory-Pro instance. In case you're contributing to the java-client capabilities that are supported by Artifactory-OSS, you can add your new tests and in order to run them, you can manually comment out tests that are relevant for Artifactory-Pro only. 
We apologise for the inconvenience and we do want to add a way to allow disabling some of the tests. Till this is implemented, we can help testing the new code. Please feel free to submit the code with the tests and we will run them before merging your code.
Thank you.

**Comment by padyx** [comment]
Thanks @eyalbe4 for the assistance.
I commented out (quite a lot) of tests and was able to run mine then. But some way to restrict them to "OSS-only" would be great, especially since they are interdependent.
I opened a new pull request for GAVC search.

**Comment by eyalbe4** [comment]
Thanks @padyx,
We will implement a way to execute OSS tests only. Thanks for the new pull request. I'm closing this one.

**Pull request closed without merging**
